import "./globals.css"
import { DM_Sans } from "next/font/google";;
import Header from "@/components/Header";
import Footer from "@/components/Footer";


const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dmSans.className}>
      <body
        data-app="true"
        data-new-gr-c-s-check-loaded="8.929.0"
        data-gr-ext-installed=""
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
